CC = gcc
CCP = g++
CFLAGS = -std=c99 -g

#problem1.o instead of problem1 for make clean to work

problem: problem1a

problem1a: problem1a.c
	$(CC) $(CFLAGS) problem1a.c -o problem1a
clean:
	rm -rf *.o
	rm -rf *.o.dSYM
